### ISSUE TITLE
Capturing PNP string

### ISSUE THREAD

**Issue by leouzz** [Raspberryy/Emulated_USB_Printer#1]
Hello nice project!
Is It possibile to have a detailed procedure how ti capture the PNP string of a own printer?
Thanks

**Comment by Raspberryy** [comment]
Thanks! I added a [detailed description](https://github.com/Raspberryy/Emulated_USB_Printer/blob/main/doc/capture_pnp_string.md) for capturing the PNP string using a windows machine. If you are using Linux you might need to look for a different USB traffic analyzer than the one I used.

It would be really cool if we could add more printers in the future. So if you want to, please sent me the PNP string, vendor id and product id if you get your printer working :)

**Comment by leouzz** [comment]
with the detailed description i was able to find the string!
now i will test it and send you all the info.
