### ISSUE TITLE
Raspberry Pi Zero W - Error opening /dev/g_printer0

### ISSUE THREAD

**Issue by mbalko** [Raspberryy/Emulated_USB_Printer#6]
Hey there,
first of all, let me thank you for this project, it is just the right thing I need right now.
However, I'm unable to make it work. I'm using Raspberry Pi Zero W with the lastest image of RPi OS Lite. After running ./emulatedprinter -get_status I get an error of "-1 opening /dev/g_printer0", although it is visible in /dev/. Any idea what I can do with it? Thanks.

**Comment by Raspberryy** [comment]
Hi :) Glad it helps! I assume you successfully connected the Pi to a USB host and started the emulation of a printer? The emulated printer is also detected by the USB host? Then you would like to receive data and this is where you are stuck... Correct up until here? 

Maybe you need root priveledges, could that maybe be?
Is there any file other then g_printer_0?
Can you check if it would work with the version I used? (Linux raspberrypi 5.4.83+ armv6l)

Keep me posted :) As I always say, I would be really interested in any projects with the printer emulation.
Regards!

**Comment by mbalko** [comment]
All I accomplished so far is flashing the SD card and changing the config.txt on /boot/ partition. I tried running it as root but it still fails on opening /dev/g_printer0 although it is present on the system. Where can I download the version you used? I'm not able to find it. Thanks.

**Comment by Raspberryy** [comment]
Thats an excellent question. I think I simply used the Raspbery Pi Imager for Windows and this is what it installed. Maybe it's cause you are using lite?

**Comment by RWAP** [comment]
I had to use chmod to set the permissions on /dev/g_printer0 to 777 for some unknown reason

**Comment by mbalko** [comment]
Using clean reinstall of the latest image of RPi OS Lite with all updates solved the problem. I'm just about to try to make this work on RPi 4, wish me luck. Also, it does require root privileges, after all it's a device file.

**Comment by mbalko** [comment]
Everything works lovely now, the key is to update rpi os and running as root.

**Comment by Raspberryy** [comment]
Glad to hear that :) Feel free to share any working printer parameters! Also, bought myself a RPi 4 a few days ago, cant wait to see how this works out.
