### ISSUE TITLE
Everything for g_printer should be right, but windows doesn't see the printer correctly

### ISSUE THREAD

**Issue by trainman313** [Raspberryy/Emulated_USB_Printer#7]
So I am trying to emulate the printer Epson Stylus CX5200 and I have the modprobe g_printer command below.

`sudo modprobe g_printer idVendor=0x04B8 idProduct=0x0808 bcdDevice=0x0100 iManufacturer="" iProduct="" iSerialNumber="" iPNPstring="MFG:EPSON;MDL:Stylus CX5200;CMD:ESCPL2,BDC,D4;C                  LASS:PRINTER;DESCRIPTION:PRINTER;DESCRIPTION:EPSON Stylus CX5200;"`

When I run this, it appears in Windows as USB Printing Support. 
![image](https://user-images.githubusercontent.com/104335690/165012368-a38a4dd5-dc25-4a23-a37b-39c5d1fa78f2.png)
It does show the printer under Device functions, but that is as far as I got. 
I'm quite new to this so sorry if it isn't formatted correctly.

**Comment by Raspberryy** [comment]
Hi :) I usually got this error whenever the USB host/the windows computer didn't have the drivers installed. In your case this probably doesn't make much sense as you seem to have one successfully connected (judging from the first image). Therefore I would guess that you are emulating the wrong printer, a printer which your PC does not recognize as one it has drivers for.

Please double check your parameters. Where did you take them from? I would suggest to use a USB traffic analyzer, something like [this one](https://www.eltima.com/products/usb-port-monitor/). It has a 14 day trial. Start the analyzer, connect the original printer and check which parameters are sent to copy these exact same parameters to your pi. Did you already do that?

Again, please feel free to share your parameters once you have it working. I will add it to [the list](https://github.com/Raspberryy/Emulated_USB_Printer/blob/main/Makefile)

Thanks!

**Comment by trainman313** [comment]
I don't actually have the printer so I used the Epson driver on Gran Turismo 4 for PS2 to get the PNP string, I then structured it to look more like the modprobe for the first hp printer in the makefile. I got the vendor id and the product id from the websites you provided. I'm sorta doing this blind without the printer.

**Comment by Raspberryy** [comment]
Okay, not super sure how reliable your method for the pnp string is. If I remember correctly, the MDL: thing seemed quite important back then when I tried. 

Few things I found, http://www.linux-usb.org/usb.ids also lists 0x0801 for the CC-600PX [Stylus CX5200/CX5400/CX6600]. Did you try that as well?

And one more thing, which doesn't tell me much, but maybe you: "Although most USB printers work fine on Linux, there are exceptions. For example the new MF devices from Epson (Stylus CX3200/CX5200) return garbage when one polls the IEEE-1284 ID string via IOCTL, for example with the code of the CUPS "usb" backend. Whereas one can poll the ID string via an Epson-proprietary method." [Source](http://mirror.internode.on.net/pub/ldp/en/Printing-HOWTO/ar01s04.html)

Do you have any other printer from Epson that might use 0x04B8 as vendorID? In that case you might be able to get the parameters for iManufacturer and iProduct. Also, this might give you hints where errors in your current pnp string might be.

**Comment by trainman313** [comment]
I did try both product IDs including the one you listed but it didn't work. About the pnp strings, I compared another ps2 Epson driver printer pnp string with one from the aggregated list and it seemed identical. In my quest in getting a printer working, I accidentally got another printer working. `sudo modprobe g_printer idVendor=0x04B8 idProduct=0x083C bcdDevice=0x0100 iManufacturer="" iProduct="" iSerialNumber="" iPNPstring="MFG:EPSON;CMD:ESCPL2,BDC,D4,D4PX,ESCPR2;MDL:Stylus Photo RX610;CLS:PRINTER;DES:Epson Stylus Photo RX610;VSTATUS:$HB0$FC0,ff,DN,IDLE,CUT;"`
This is for the Epson Stylus Photo RX610.

**Comment by Raspberryy** [comment]
Awesome, added it to the Makefile already. Will this allow you to continue your project? Would love to hear what your are using this for. Anyway, good luck and lots of fun! :)

**Comment by Raspberryy** [comment]
If I am not mistaken, you can also manually assign drivers to the emulated printer on the hosts site. So if you have access to do that for the USB Host/your computer, you might want to try your initial parameters (or probably any other parameters) connect it, make sure the pi shows up as Printer Gadget, manually assign drivers of the Epson Stylus CX5200 et voila, it should be an Epson printer now. As I said, it is very likely this is due to the wrong parameters. I you agree, do we want to close this issue then? Regards!

**Comment by trainman313** [comment]
I apologize for not responding in a while. I was busy with real life stuff. To answer your previous question, I planned to use it on PS2 to emulate a supported printer to try a printing function a game had. For the printer drivers, I bought one of the printers I was trying to emulate and saw that a driver fix thing appeared in windows update for the specific model of printer. At first the printer I bought wasn't working but was fixed by doing the windows update driver thing. I may eventually get the pnp string working but since I am still pretty busy I don't have the time. I'll close the issue since I believe the windows update driver may be the solution.
